arch:
  - aarch64
  - amd64
description:
  Extracts completed downloads for the arr applications. Unpackerr watches what
  Radarr and Sonarr are waiting on, unpacks archives in place, and cleans up
  once they have been imported.
image: 'ghcr.io/kanso-labs/home-assistant-application-unpackerr'
init: false
map:
  - read_only: false
    type: app_config
  - read_only: false
    type: media
  - read_only: false
    type: share
name: Unpackerr
slug: unpackerr
url: 'https://github.com/kanso-labs/home-assistant-applications/tree/main/unpackerr'
version: '1.2.1' # x-release-please-version
